### ISSUE TITLE
Need to update card for DNS

### ISSUE THREAD

**Issue by chadwhitacre** [AspenWeb/salon#15]
My credit card number changed and I neglected to update it at DNSimple, our DNS provider for aspen.io. I am traveling and don't have my personal card on hand. I will try to remember to call home to get it.

> We'll try again. We'll try to bill your account three more times. If billing fails on the fourth attempt, your account will be deactivated until you contact us to update your credit card.

@Changaco Do you run a DNS server? Or do you have another better DNS option for us, perchance? :)

**Comment by Changaco** [comment]
I don't run an authoritative DNS server myself (though I will need one for [oy.lc](http://oy.lc/)). All my domains are managed by [Gandi](https://www.gandi.net/) (they've had a good reputation since forever and support some open source projects), although Liberapay's DNS is delegated to [CloudFlare](https://www.cloudflare.com/) (it's free).

**Comment by chadwhitacre** [comment]
Okay, I will probably try to fix my card at DNSimple later today as the path of least resistance here.

**Comment by chadwhitacre** [comment]
Called home, waiting to hear back ...

**Comment by chadwhitacre** [comment]
Updated!
